Don't hard code std=c++14 in CXX_FLAGS
I got the following build error

"src/checks/level2/missing-qobject-macro.cpp:93:43:
error: 'std::filesystem' has not been declared".

I'm pretty sure that my compiler (gcc 11.2.0) supports it and cmake
seems to agree and defines -DHAS_STD_FILESYSTEM. It turns out that
the manual addition of "-std=c++14" to CMAKE_CXX_FLAGS overwrote
"CMAKE_CXX_STANDARD 17" here. Seems generally nicer to only have that
in one place and it also fixes the previously mentioned build error.