Require c++17, some compilers can't build clazy in c++14 mode
As reported by Krop:
    /home/abuild/rpmbuild/BUILD/clazy-1.9/src/SourceCompatibilityHelpers.h:122:12: error: call to deleted constructor of 'clang::Lexer'
    [   90s]     return clang::Lexer(id, inputFile.getValue(), sm, lo);